# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='shortcode',
            field=models.CharField(default='blabla', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorturl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorturl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
